/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:58cda742-7009-44c4-8ac7-845fbd692b65",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_rYQz88ddN",
    "aws_user_pools_web_client_id": "4vrdvsfbdcjm2ih97ufjhq7r39",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "instapatf86ffd5cbde4479d9f4ca3e46ceaef9d122940-dev",
    "aws_user_files_s3_bucket_region": "us-west-1",
    "aws_dynamodb_all_tables_region": "us-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "instaPatDB-dev",
            "region": "us-west-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "intaPat",
            "endpoint": "https://lu45yok183.execute-api.us-west-1.amazonaws.com/dev",
            "region": "us-west-1"
        }
    ]
};


export default awsmobile;
